gift::parameters Class Reference
#include <gift.hpp>
Public Member Functions
parameters (const std::string) throw (std::string)
int setDrugNum (int number)
int setSubNum (int number)
int setProteinNum (int number)
int setDomainNum (int number)
int InitDrugSub2ProteinSub ()
int InitVarDrugSub2ProteinSub ()
int InitDrugName2Index ()
int InitProteinName2Index ()
int InitDrugSubNameList ()
int InitProteinSubNameList ()
int InitPredictParameters () throw (std::string)
int InitObservedDrug2ProteinMatrix ()
Public Attributes
std::string drug2proteinFileName
std::string drug2subFileName
std::string protein2subFileName
std::string drugSub2proteinSubFileName
std::string drugNameListFile
std::string drugSubNameListFile
std::string proteinNameListFile
std::string proteinSubNameListFile
bool loglikelyRecord
double alphaEB
double betaEB
double fn
double fp
int thread
int iterNum
int drugNum
int subNum
int domainNum
int proteinNum
std::string inputDelims
std::string task
std::string chemfpRec
std::string proteinfpRec
std::string CPIsRec
std::string predictDrugsFileName
std::string predictProteinsFileName
std::string predictDrugsFileName_WithSubs
std::string predictProteinsFileName_WithSubs
std::string outputDelims
std::string outRecordFileName
std::string outPredictCPIsFileName
std::string outDrugSub2ProteinSubFileName
std::string outVarDrugSub2proteinSubFileName
Constructor & Destructor Documentation
gift::parameters::parameters (const std::string configFile) throw std::string)
References gift::BoolToString(), gift::rowCol::colNum, gift::Matrix2Fingerpints(), gift::Matrix2FingerprintsByColumn(), gift::printIntArrayList(), gift::rowColFile(), and gift::rowCol::rowNum.
                                                                    {
    std::cout<<"Now set parameters with configFile."<<std::endl;
    // use boost program_options to read configs from a given file.
    namespace po = boost::program_options;
    po::options_description desc("GIFT Parameter options");
    desc.add_options()
      // input data file name
      ("drug2proteinFileName",
       po::value<std::string>(&drug2proteinFileName),
       "file name for drug protein interactions")
      ("drug2subFileName",po::value<std::string>(&drug2subFileName),
       "file name for drug to substructure")
      ("protein2subFileName",po::value<std::string>(&protein2subFileName),
       "file name for protein to substructure")
      ("drugSub2proteinSubFileName",
       po::value<std::string>(&drugSub2proteinSubFileName),
       "file name for drugSub to proteinSub interaction probability")
      // input name list file name
      ("drugNameListFile",po::value<std::string>(&drugNameListFile),
       "file name for drug names")
      ("drugSubNameListFile",po::value<std::string>(&drugSubNameListFile),
       "file name for drug substructures names")
      ("proteinNameListFile",po::value<std::string>(&proteinNameListFile),
       ("file name for protein names"))
      ("proteinSubNameListFile",po::value<std::string>(&proteinSubNameListFile),
       "file name for protein substructures names")
      // input parameters for EM
      ("alphaEB",po::value<double>(&alphaEB)->default_value(0.05),
       "parameter for Empirical Bayesian estimates for initEM")
      ("betaEB",po::value<double>(&betaEB)->default_value(0.05),
       "parameter for Empirical Bayesian estimates for initEM")
      ("fp", po::value<double>(&fp)->default_value(0.85),
       "false positive rate")
      ("fn", po::value<double>(&fn)->default_value(0.0001),
       "false negative rate")
      ("threadNum", po::value<int>(&thread)->default_value(1),
       "thread number for EM")
      ("EMIterationNum", po::value<int>(&iterNum)->default_value(300),
       "iteration numbers for EM")
      ("task", po::value<std::string>(&task)->default_value("train"),
       "run gift for train or predict")
      ("loglikelyRecord",
       po::value<bool>(&loglikelyRecord)->default_value(false),
       "whether or not to record the loglikely in every step")
      ("inputDelims",po::value<std::string>(&inputDelims)->default_value("\t,"),
       "sep character for input files")
      // input file version information.
      ("chemFingerPrintRecord",
       po::value<std::string>(&chemfpRec)->default_value("ComFP: PUBCHEM"),
       "source and version of chemical fingerprints")
      ("proteinFingerPrintRecord",
       po::value<std::string>(&proteinfpRec)->default_value("Pfam: 2011-07"),
       "source and version of protein fingerprints/domains")
      ("comProteinInteractionRecord",
       po::value<std::string>(&CPIsRec)->default_value("DrugBank: 2011-07"),
       "source and version of compound-protien interactions")
      // input file names for prediction
      ("predictDrugsFileName",po::value<std::string>(&predictDrugsFileName),
       "file name for drug names used for prediciton by gift")
      ("predictProteinFileName",po::value<std::string>(&predictProteinsFileName),
       "file name for protein names used for prediction by gift")
      ("predictDrugsFileName_WithSubs",
       po::value<std::string>(&predictDrugsFileName_WithSubs),
       "file name for drugs names together with their substructures.")
      ("predictProteinsFileName_WithSubs",
       po::value<std::string>(&predictProteinsFileName_WithSubs),
       "file name for protein names together with their substructures.")
      // output file name and format
      ("outputDelims",po::value<std::string>(&outputDelims)->default_value("\t,"),
       "sep character for output files")
      ("outRecordFileName",
       po::value<std::string>(&outRecordFileName)->default_value("CPIs"),
       "file name for output records")
      ("outPredictCPIsFileName",
       po::value<std::string>(&outPredictCPIsFileName),
       "file name for output CPIs")
      ("outDrugSub2ProteinSubFileName",
       po::value<std::string>(&outDrugSub2ProteinSubFileName),
       "file name for output drugSub2proteinSub")
      ("outVarDrugSub2proteinSubFileName",
       po::value<std::string>(&outVarDrugSub2proteinSubFileName),
       "file name for output variance of drugSub2proteinSub");
    po::variables_map vm;
    std::ifstream input (configFile, std::ios::in);
    po::store(po::parse_config_file(input, desc), vm);
    po::notify(vm);
    // input.exceptions(std::ifstream::failbit | std::ifstream::badbit);
    // try {
    // input.open(configFile, std::ifstream::in);
    // if (input.peek() == std::ifstream::traits_type::eof()) {
    // std::cerr<<configFile<<" is empty." << std::endl;
    // } // end of if.
    // po::store(po::parse_config_file(input, desc), vm);
    // po::notify(vm);
    // } catch (std::ifstream::failure e) {
    // std::cerr <<"Exceptions open/read file "<<configFile<<std::endl;
    // } // end of try catch
    // default training data parameters.
    // they will be set when read data files.
    rowCol tmp;
    rowColFile(drug2subFileName,tmp,inputDelims);
    drugNum = tmp.rowNum;
    subNum = tmp.colNum;
    std::cout<<"Drug Number is "<<drugNum<<std::endl;
    std::cout<<"DrugSub Number is "<<subNum<<std::endl;
    rowColFile(protein2subFileName,tmp,inputDelims);
    domainNum = tmp.colNum;
    proteinNum = tmp.rowNum;
    std::cout<<"Protein Number is "<<proteinNum<<std::endl;
    std::cout<<"ProteinSub Number is "<<domainNum<<std::endl;
    // load global data for gift.
    Matrix2Fingerpints(drug2proteinFileName,
      drug2proteinList,inputDelims);
    //printIntArrayList(drug2proteinList); // for test
    Matrix2Fingerpints(protein2subFileName,
      protein2domainList,inputDelims);
    //printIntArrayList(protein2domainList); // for test
    Matrix2Fingerpints(drug2subFileName,
      drug2subList,inputDelims);
    //printIntArrayList(drug2subList); // for test
    IntList tmpIntArray;
    std::cout<<"Initialize the sub2drugList..."<<std::endl;
    Matrix2FingerprintsByColumn(drug2subFileName,
      sub2drugList,subNum,inputDelims);
    std::cout<<"Finish the init of sub2drugList."<<std::endl;
    printIntArrayList(sub2drugList); // for test
    std::cout<<"Initialize the domain2proteinList..."<<std::endl;
    Matrix2FingerprintsByColumn(protein2subFileName,
      domain2proteinList,
                                domainNum, inputDelims);
    std::cout<<"Finish the init of domain2proteinList."<<std::endl;
    printIntArrayList(domain2proteinList); // for test
    InitDrugSub2ProteinSub();
    InitVarDrugSub2ProteinSub();
    InitObservedDrug2ProteinMatrix();
    // load NameList.
    InitDrugName2Index();
    InitProteinName2Index();
    InitDrugSubNameList();
    InitProteinSubNameList();
    // load predicted name list and possible subs if task is prediction.
    InitPredictParameters(); // throw std::string.
    // print the setting results.
    std::cout<<"parameters have been set."<<std::endl;
    for (const auto& it : vm){
      std::cout<< it.first.c_str() << ": ";
      auto& value = it.second.value(); // return boost::any reference type.
      // any_cast use the any * as input and return the pointer with type infor.
      if (auto v = boost::any_cast<int>(&value)) {
        std::cout<< *v <<std::endl;
      } else if (auto v = boost::any_cast<double>(&value)) {
        std::cout<< *v <<std::endl;
      } else if (auto v = boost::any_cast<bool>(&value)) {
        std::cout<< BoolToString(*v) <<std::endl;
      } else if (auto v = boost::any_cast<std::string>(&value)) {
        std::cout<< *v <<std::endl;
      } else {
        std::cout<< "Error type"<<std::endl;
      } // end of if
    } // end of for
    std::cout<<"drugNum: " <<drugNum<<std::endl;
    std::cout<<"subNum: "<<subNum<<std::endl;
    std::cout<<"domainNum: "<<domainNum<<std::endl;
    std::cout<<"proteinNum: "<<proteinNum<<std::endl;
  } // end of class parameter constructor.
Member Function Documentation
int gift::parameters::InitDrugName2Index ()
References drugNameListFile, gift::readName2IndexHash(), and gift::readNameListFromFile().
                                     {
    std::cout<<"Initialize DrugName2Index Hash..."<<std::endl;
    readNameListFromFile(drugNameListFile,
      drugNameList);
    readName2IndexHash(drugNameList,drugName2Index);
    std::cout<<"Finish DrugName2Index Hash."<<std::endl;
    return 0;
  } // end of function
int gift::parameters::InitDrugSub2ProteinSub ()
References alphaEB, betaEB, domainNum, drugSub2proteinSubFileName, inputDelims, gift::readMatrix(), subNum, and task.
                                        {
    // This function must be run after class parameter initionlization.
    std::cout<< "Initialize the drugSub2proteinSub Matrix." << std::endl;
    if (task.compare("predict") == 0) {
      readMatrix(drugSub2proteinSubFileName,
      drugSub2proteinSubMatrix,
                 inputDelims);
      std::cout<< "Finish: read from file."<<std::endl;
    } else {
      std::vector<double> assoTmp; // temp array based on the assocaiton method.
      int N;
      int subNumTmp;
      int I = 0;
      std::vector<int>::iterator it;
      for (int i=0;i<subNum;++i){
        subNumTmp = sub2drugList[i].size();
        for (int j=0;j<domainNum;++j){
          N = domain2proteinList[j].size() * subNumTmp;
          for (const auto drug : sub2drugList[i]){
            for (const auto protein : domain2proteinList[j]){
              it = std::find(drug2proteinList[drug].begin(),
                             drug2proteinList[drug].end(), protein);
              I += (it==drug2proteinList[drug].end() ? 0 : 1);
            } // end of loop protein
          } // end of loop drug
          // revise association method with Emiprical Bayes.
          assoTmp.push_back((I+alphaEB)/(alphaEB+betaEB+N));
          I = 0;
        } // end of loop j
        drugSub2proteinSubMatrix.push_back(assoTmp);
        assoTmp.clear();
      } // end of loop i
      std::cout<<"Finish: initialize with associatiom method and emprical Bayes."
               <<std::endl;
    } // end of if else
    return 0;
  } // end of function
int gift::parameters::InitDrugSubNameList ()
References drugSubNameListFile, and gift::readNameListFromFile().
                                      {
    readNameListFromFile(drugSubNameListFile,
      drugSubNameList);
    return 0;
  } // end of function
int gift::parameters::InitObservedDrug2ProteinMatrix ()
References drugNum, proteinNum, and task.
                                                {
    std::cout<<"Init ObservedDrug2ProteinMatrix ..."<<std::endl;
    if(task.compare("predict") == 0){
      std::cout<<"Job is to predict, and ignore the inition of observedDrug2Protein."
               <<std::endl;
    } else{
      std::vector<double> tmpArray(proteinNum,0.1);
      for(int i=0;i<drugNum;++i){
        observedDrug2ProteinMatrix.push_back(tmpArray);
      } // end of loop for i.
    } // end of if else
    std::cout<<"Finish the init of observedDrug2ProteinMatrix."<<std::endl;
    return 0;
  } // end of function.
int gift::parameters::InitPredictParameters () throw std::string)
References predictDrugsFileName, predictDrugsFileName_WithSubs, predictProteinsFileName, predictProteinsFileName_WithSubs, gift::readNameListFromFile(), and gift::readNameMatrixFromFile().
                                                         {
    // when task is predict, we use this function to init the corresponding
    // parameters.
    bool checkStatus = false;
    if (!predictDrugsFileName.empty()){
      checkStatus = true;
      readNameListFromFile(predictDrugsFileName,
      predictDrugNameList);
    } // end of if for drugfile
    if (!predictProteinsFileName.empty()){
      checkStatus = true;
      readNameListFromFile(predictProteinsFileName,
      predictProteinNameList);
    } // end of if for proteinfile
    if (!predictDrugsFileName_WithSubs.empty()){
      checkStatus = true;
      // NEED FUNCTION.
      readNameMatrixFromFile(predictDrugsFileName_WithSubs
      ,
                             predictDrugNameList_WithSubs,
                             predictDrug2SubList);
    } // end of if for drug_withsubs file.
    if (!predictProteinsFileName_WithSubs.empty()){
      checkStatus = true;
      // NEED FUNCTION.
      readNameMatrixFromFile(
      predictProteinsFileName_WithSubs,
                             predictProteinNameList_WithSubs,
                             predictProtein2SubList);
    } // end of if for protein_withsubs file.
    if (!checkStatus){
      throw("Task for prediction, but no predicted files!");
    } // end of if for checkStatus.
    return 0;
  } // end of function
int gift::parameters::InitProteinName2Index ()
References proteinNameListFile, gift::readName2IndexHash(), and gift::readNameListFromFile().
                                        {
    readNameListFromFile(proteinNameListFile,
      proteinNameList);
    readName2IndexHash(proteinNameList,
      proteinName2Index);
    return 0;
  } // end of function
int gift::parameters::InitProteinSubNameList ()
References proteinSubNameListFile, and gift::readNameListFromFile().
                                         {
    readNameListFromFile(proteinSubNameListFile,
      proteinSubNameList);
    return 0;
  } // end of function
int gift::parameters::InitVarDrugSub2ProteinSub ()
References domainNum, subNum, and task.
                                           {
    if (task.compare("predict") == 0) {
      std::cout<< "Job is to predict, skip init variance matrix." << std::endl;
    } else {
      std::cout<<"Initialize the variance matrix for drugSub2ProteinSub..."
               <<std::endl;
      std::vector<double> tmpArray (domainNum,1.01);
      for(int i=0;i<subNum;++i){
        vardrugSub2proteinSubMatrix.push_back(tmpArray);
      } // end of loop for i.
    } // end of if else
    std::cout<<"Finish init of variance matrix for drugSub2ProteinSub." <<std::endl;
    return 0;
  } // end of function
int gift::parameters::setDomainNum (int number) [inline]
{ domainNum = number; return 0; }
int gift::parameters::setDrugNum (int number) [inline]
{ drugNum = number; return 0; }
int gift::parameters::setProteinNum (int number) [inline]
{proteinNum = number; return 0; }
int gift::parameters::setSubNum (int number) [inline]
{ subNum = number; return 0; }
Member Data Documentation
double gift::parameters::alphaEB
Referenced by InitDrugSub2ProteinSub().
double gift::parameters::betaEB
Referenced by InitDrugSub2ProteinSub().
std::string gift::parameters::chemfpRec
std::string gift::parameters::CPIsRec
int gift::parameters::domainNum
Referenced by InitDrugSub2ProteinSub(), and InitVarDrugSub2ProteinSub().
std::string gift::parameters::drug2proteinFileName
std::string gift::parameters::drug2subFileName
std::string gift::parameters::drugNameListFile
Referenced by InitDrugName2Index().
int gift::parameters::drugNum
Referenced by InitObservedDrug2ProteinMatrix().
std::string gift::parameters::drugSub2proteinSubFileName
Referenced by InitDrugSub2ProteinSub().
std::string gift::parameters::drugSubNameListFile
Referenced by InitDrugSubNameList().
double gift::parameters::fn
double gift::parameters::fp
std::string gift::parameters::inputDelims
Referenced by InitDrugSub2ProteinSub().
int gift::parameters::iterNum
bool gift::parameters::loglikelyRecord
Referenced by gift::outRecord().
std::string gift::parameters::outDrugSub2ProteinSubFileName
std::string gift::parameters::outPredictCPIsFileName
std::string gift::parameters::outputDelims
std::string gift::parameters::outRecordFileName
Referenced by gift::outRecord().
std::string gift::parameters::outVarDrugSub2proteinSubFileName
std::string gift::parameters::predictDrugsFileName
Referenced by InitPredictParameters().
std::string gift::parameters::predictDrugsFileName_WithSubs
Referenced by InitPredictParameters().
std::string gift::parameters::predictProteinsFileName
Referenced by InitPredictParameters().
std::string gift::parameters::predictProteinsFileName_WithSubs
Referenced by InitPredictParameters().
std::string gift::parameters::protein2subFileName
std::string gift::parameters::proteinfpRec
std::string gift::parameters::proteinNameListFile
Referenced by InitProteinName2Index().
int gift::parameters::proteinNum
Referenced by InitObservedDrug2ProteinMatrix().
std::string gift::parameters::proteinSubNameListFile
Referenced by InitProteinSubNameList().
int gift::parameters::subNum
Referenced by InitDrugSub2ProteinSub(), and InitVarDrugSub2ProteinSub().
std::string gift::parameters::task
Referenced by InitDrugSub2ProteinSub(), InitObservedDrug2ProteinMatrix(), InitVarDrugSub2ProteinSub(), main(), and gift::outRecord().
int gift::parameters::thread
The documentation for this class was generated from the following files:
gift.hpp
parameterGift.cpp