gift Namespace Reference
Classes
class EM
class parameters
class rowCol
Typedefs
typedef std::vector< int > IntList
typedef std::vector< std::vector< int > > IntArrayList
typedef std::vector< std::vector< double > > numericMatrix
typedef std::map< std::string, int > name2IndexHash
typedef std::vector< std::string > nameList
Functions
int Matrix2Fingerpints (const std::string inputFile, IntArrayList &getFp, std::string delims)
int readMatrix (const std::string inputFile, numericMatrix &getMat, std::string delims)
int rowColFile (const std::string inputFile, rowCol &matrixRec, std::string delims)
int writeMatrix (const std::string outFileName, numericMatrix &resultMat, std::string delims)
int printIntArrayList (const IntArrayList &fromIntArrayList)
int printMatrix (const numericMatrix &fromMatrix)
int readNameListFromFile (const std::string inputFile, nameList &tonameList)
int readNameMatrixFromFile (const std::string inputFile, nameList &tonameList, IntArrayList &getFP, std::string delims)
int readName2IndexHash (const nameList fromNameList, name2IndexHash &name2Index)
int getIndexFromHash (const name2IndexHash &name2Index, const nameList fromNameList, IntList &toIndexList, nameList &existNameList)
int helpGift ()
int outRecord (parameters &EMparameters)
int Matrix2FingerprintsByColumn (const std::string inputFile, IntArrayList &getFP, int rowNum, std::string delims)
const std::string author (`Songpeng Zu`)
const std::string email (`zusongpeng@gmail.com`)
const std::string version (`gift-2.0`)
const std::string updateTime (`2016-03-06`)
template<typename func >
int functionThread (func useFun, int thread, EM *point)
const char * BoolToString (bool b)
Variables
const int recLogLeastNum = 5
IntArrayList drug2proteinList
IntArrayList drug2subList
IntArrayList sub2drugList
IntArrayList protein2domainList
IntArrayList domain2proteinList
numericMatrix drugSub2proteinSubMatrix
numericMatrix observedDrug2ProteinMatrix
numericMatrix vardrugSub2proteinSubMatrix
std::vector< double > loglikelyArray
name2IndexHash drugName2Index
name2IndexHash proteinName2Index
nameList drugNameList
nameList proteinNameList
nameList drugSubNameList
nameList proteinSubNameList
nameList predictDrugNameList
nameList predictProteinNameList
nameList predictDrugNameList_WithSubs
nameList predictProteinNameList_WithSubs
IntArrayList predictDrug2SubList
IntArrayList predictProtein2SubList
Typedef Documentation
typedef std::vector<std::vector<int> > gift::IntArrayList
typedef std::vector<int> gift::IntList
typedef std::map<std::string,int> gift::name2IndexHash
typedef std::vector<std::string> gift::nameList
typedef std::vector<std::vector<double> > gift::numericMatrix
Function Documentation
const std::string gift::author (`Songpeng Zu`)
Referenced by helpGift(), and outRecord().
const char* gift::BoolToString (bool b) [inline]
Referenced by gift::parameters::parameters().
                                           {
    return b ? "true" : "false";
  } // end of function BoolToString
const std::string gift::email (`zusongpeng@gmail.com`)
Referenced by helpGift(), and outRecord().
template<typename func > int gift::functionThread (func useFun, int thread, EM * point)
Referenced by gift::EM::EStep(), and gift::EM::MStep().
                                                         {
    boost::thread * y;
    boost::thread_group * x = new boost::thread_group;
    for(int i=0;i<thread;++i){
      y = new boost::thread(useFun,point,i);
      x->add_thread(y);
    } // end of loop i
    x->join_all();
    delete x;
    return 0;
  } // end of function.
int gift::getIndexFromHash (const name2IndexHash & name2Index, const nameList fromNameList, IntList & toIndexList, nameList & existNameList)
Referenced by gift::EM::predictDrugs(), gift::EM::predictDrugsProteins(), gift::EM::predictDrugsProteinsWithSubs(), gift::EM::predictDrugsWithSubsProteins(), and gift::EM::predictProteins().
                                                {
    for(const auto fromName : fromNameList){
      if (name2Index.find(fromName) != name2Index.end()){
        existNameList.push_back(fromName);
        toIndexList.push_back((name2Index.find(fromName))->second);
      } else {
        std::cout<<"Cannot find the key " << fromName
                 <<" fromNameList. Continue..." <<std::endl;
      } // end of if else
    } // end of loop fromNameList
    return 0;
  } // end of function
int gift::helpGift ()
References author(), email(), updateTime(), and version().
Referenced by main().
                {
    // Output gift information and useness to standard output.
    // Basic information about gift.
    std::cout<<"Gift is used to predict compound-protein interactions based on "
             <<std::endl;
    std::cout<<"their substructures interactions."<<std::endl;
    std::cout<<"It is also used to infer the substructres interactions from"
             <<std::endl;
    std::cout<<" the known drug-protein interactions."<<std::endl;
    std::cout<<"If you want to know more about gift, please read the paper: "
             <<std::endl;
    std::cout<<"Global Optimization-based Inference of Chemogenomic Features "
             <<std::endl;
    std::cout<<"from Drug-Target Interactions, which is published "<<std::endl;
    std::cout<<"on Bioinformatics, 2015. "<<std::endl;
    std::cout<<"Author: "<<author<<std::endl;
    std::cout<<"Email: " <<email<<std::endl;
    std::cout<<"Current version: "<<version<<std::endl;
    std::cout<<"Last update time: "<<updateTime<<std::endl;
    std::cout<<"You can get the C++ source code from: "<<std::endl;
    std::cout<<"https://github.com/songpeng/GIFT" << std::endl;
    std::cout<<std::endl;
    //Input parameters
    std::cout<<"--help | -h to show the help information of gift."<<std::endl;
    std::cout<<"--version | -v to show the version information of gift."
             <<std::endl;
    std::cout<<"Gift need one configure file for its running."<<std::endl;
    std::cout<<"Please use --config to tell gift the configure file name."
             <<std::endl;
    std::cout<<"The content in the configure file are listed below: "<<std::endl;
    // configure file information.
    std::cout<<"[INPUT DATA FILE NAMES]" <<std::endl;
    std::cout<<"drug2proteinFileName=<string> : "
             <<"file name for drug protein interactions" <<std::endl;
    std::cout<<"drug2subFilename=<string> : "
             <<"file name for drug to substructure" <<std::endl;
    std::cout<<"protein2subFileName=<string> : "
             <<"file name for protein to substructure" << std::endl;
    std::cout<<"drugSub2proteinSubfilename=<string> : "
             <<"file name for drugSub to proteinSub interaction probability."
             <<std::endl;
    std::cout<<"drugNameListFile=<string> : "
             <<"file name for drug names" << std::endl;
    std::cout<<"drugSubNameListFile=<string> : "
             <<"file name for drug substructures names." << std::endl;
    std::cout<<"proteinNameListFile=<string> : "
             <<"file name for protein names" << std::endl;
    std::cout<<"proteinSubNameListFile=<string> : "
             <<"file name for protein substructures names." << std::endl;
    std::cout<<"[INPUT PARAMETERS FOR EM ALGORITHM]" <<std::endl;
    std::cout<<"alphaEB=<double> : "
             <<"parameter for Empricial Bayesian estimates for initEM."
             <<std::endl;
    std::cout<<"betaEB=<double> : "
             <<"parameter for Empricial Bayesian estimates for initEM."
             <<std::endl;
    std::cout<<"fp=<double> : "<<"false positive rate"<<std::endl;
    std::cout<<"fn=<double> : "<<"false negative rate"<<std::endl;
    std::cout<<"threadNum=<int> : "<<"thread number for EM." <<std::endl;
    std::cout<<"EMIterationNum=<int> : "<<"iteration numbers/steps for EM."<<std::endl;
    std::cout<<"task=<string> : "<<"run gift for [train] or [predict]."<<std::endl;
    std::cout<<"loglikelyRecord=<string> : "<<
      "record [true] or not [false] the loglikely in in every step."<<std::endl;
    std::cout<<"inputDelims=<string> : "
             <<"sep character for input files, such as '\t',',' "<<std::endl;
    std::cout<<"[INPUT FILE VERSION INFORMATION]"<<std::endl;
    std::cout<<"chemFingerPrintRecord=<string> : "
             <<"source and version of chemical fingerprints."<<std::endl;
    std::cout<<"proteinFingerPrintRecord=<string> : "
             <<"source and version of protein fingerpints/domains."<<std::endl;
    std::cout<<"comProteinInteractionRecord=<string> : "
             <<"source and version of compound-protein interactions."<<std::endl;
    std::cout<<"[INPUT FILE NAME FOR PREDICTION]"<<std::endl;
    std::cout<<"predictDrugsFileName=<string> : "
             <<"file name for drug names used for prediction by gift."<<std::endl;
    std::cout<<"predictProteinsFileName=<string> : "
             <<"file name for protein names used for prediction by gift."<<std::endl;
    std::cout<<"predictDrugsFileName_WithSubs=<string> : "
             <<"file name for drug names together with their substructures."
             <<std::endl;
    std::cout<<"predictProteinsFileName_WithSubs=<string> : "
             <<"file name for protein names together with their substructures."
             <<std::endl;
    std::cout<<"[OUTPUT FILE NAME AND FORMAT]"<<std::endl;
    std::cout<<"outputDelims=<string> : "
             <<"sep character for output files." <<std::endl;
    std::cout<<"outRecordFileName=<string> : "<<"file name for output records."
             <<std::endl;
    std::cout<<"outPredictCPIsFileName=<string> : "
             <<"file name for output CPIs." <<std::endl;
    std::cout<<"outDrugSub2ProteinSubFileName=<string> : "
             <<"file name for output drugSub2proteinSub matrix."<<std::endl;
    std::cout<<"outVarDrugSub2proteinSubFileName=<string> : "
             <<"file name for output variance of drugSub2proteinSub." <<std::endl;
    return 0;
  } // end of function
int gift::Matrix2Fingerpints (const std::string inputFile, IntArrayList & getFp, std::string delims)
Referenced by gift::parameters::parameters().
                                          {
    std::ifstream input (inputFile, std::ios::in);
    std::string line;
    std::vector<std::string> array;
    std::vector<int> tempRec;
    while (std::getline(input,line)) {
      boost::algorithm::split(array,line,boost::is_any_of(delims));
      int arraylen = array.size();
      for (int i=0;i<arraylen;++i) {
        if (array[i].compare("1") == 0) {
          tempRec.push_back(i);
        }// end of if
      } // end of for
      getFp.push_back(tempRec);
      tempRec.clear();
    } // end of while
    // input.exceptions(std::ifstream::failbit | std::ifstream::badbit);
    // try {
    // input.open(inputFile, std::ifstream::in);
    // if (input.peek() == std::ifstream::traits_type::eof()){
    // std::cerr <<inputFile <<" is empty. " <<std::endl;
    // return 1;
    // } // end of if
    // while (std::getline(input,line)) {
    // boost::algorithm::split(array,line,boost::is_any_of(delims));
    // int arraylen = array.size();
    // for (int i=0;i<arraylen;++i) {
    // if (array[i].compare("1") == 0) {
    // tempRec.push_back(i);
    // }// end of if
    // } // end of for
    // getFp.push_back(tempRec);
    // tempRec.clear();
    // } // end of while
    // } catch (std::ifstream::failure e) {
    // std::cerr <<"Exceptions open/read file "<<inputFile<<std::endl;
    // return 1;
    // } // end of catch
    return 0;
  } // end of function.
int gift::Matrix2FingerprintsByColumn (const std::string inputFile, IntArrayList & getFP, int rowNum, std::string delims)
Referenced by gift::parameters::parameters().
                                                   {
    std::ifstream input (inputFile, std::ios::in);
    std::string line;
    std::vector<std::string> array;
    int linenum = 0;
    // init getFP first.
    std::cout<<"Init getFP IntArrayList..."<<std::endl;
    std::vector<int> tmpArray;
    for(int i=0;i<rowNum;++i) {
      getFP.push_back(tmpArray);
    } // end of loop
    std::cout<<"End of Init getFP IntArrayList."<<std::endl;
    while (std::getline(input,line)){
      boost::algorithm::split(array,line,boost::is_any_of(delims));
      int arraylen = array.size();
      for (int i=0;i<arraylen;++i){
        if (array[i].compare("1") == 0){
          getFP[i].push_back(linenum);
        } // end of if
      } // end of loop for i
      linenum += 1;
      array.clear();
    } // end of while for file read.
    // input.exceptions(std::ifstream::failbit | std::ifstream::badbit);
    // try {
    // input.open(inputFile,std::ifstream::in);
    // if(input.peek() == std::ifstream::traits_type::eof()){
    // std::cerr<< inputFile << " is empty. "<<std::endl;
    // return 1;
    // } // end of if
    // // init getFP first.
    // for(int i=0;i<rowNum;++i) {
    // std::vector<int> tmpArray;
    // getFP.push_back(tmpArray);
    // } // end of loop
    // // read file.
    // while (std::getline(input,line)){
    // boost::algorithm::split(array,line,boost::is_any_of(delims));
    // int arraylen = array.size();
    // for (int i=0;i<arraylen;++i){
    // if (array[i].compare("1") == 0){
    // getFP[i].push_back(linenum);
    // } // end of if
    // } // end of loop for i
    // linenum += 1;
    // } // end of while for file read.
    // } catch (std::ifstream::failure e) {
    // std::cerr<<"Exceptions open/read file "<<inputFile<<std::endl;
    // return 1;
    // } // end of catch
    return 0;
  } // end of function
int gift::outRecord (parameters & EMparameters)
References author(), email(), loglikelyArray, gift::parameters::loglikelyRecord, gift::parameters::outRecordFileName, gift::parameters::task, updateTime(), and version().
Referenced by main().
                                          {
    std::ofstream output (EMparameters.outRecordFileName,std::ofstream::out);
    if (!output.is_open()){
      std::cerr<<"Error open file "<<EMparameters.outRecordFileName<<std::endl;
      return 1;
    }// end of if
    // Basic information about gift.
    output<<"The author of gift is " << author <<std::endl;
    output<<"Contact information: " << email <<std::endl;
    output<<"Current gift's version is "<< version <<std::endl;
    output<<"Update time is " << updateTime <<std::endl;
    // Running information.
    std::chrono::system_clock::time_point timePos =
      std::chrono::system_clock::now();
    std::time_t timePosT = std::chrono::system_clock::to_time_t(timePos);
    output<<"The job destination is "<<EMparameters.task;
    output<<", which is finished at "<<std::ctime(&timePosT) <<std::endl;
    if(EMparameters.task.compare("train") == 0){
      if(EMparameters.loglikelyRecord){
        output<<"The loglikelyhood values are followed: "<<std::endl;
        for(const auto m : loglikelyArray){
          output<<m<<std::endl;
        } // end of loop for m.
      } // end of if
    } // end of if
    output.close();
    return 0;
  } // end of function
int gift::printIntArrayList (const IntArrayList & fromIntArrayList)
Referenced by gift::parameters::parameters().
                                                             {
    int lineNum = fromIntArrayList.size();
    for(int i=0;i<lineNum;++i){
      if (fromIntArrayList[i].empty()){
        std::cerr<<"[ERROR]: Row "<<i<<" is empty for printing... "<<std::endl;
        return 1;
      } // end of if
      for(const auto m : fromIntArrayList[i]){std::cout<<m<<",";}
      std::cout<<std::endl;
    } // end of loop for i
    return 0;
  } // end of function.
int gift::printMatrix (const numericMatrix & fromMatrix)
                                                  {
    int rowNum = fromMatrix.size();
    int colNum = fromMatrix[0].size();
    for(int i=0;i<rowNum;++i){
      for(int j=0;j<colNum;++j){
        std::cout<<fromMatrix[i][j]<<",";
      } // end of loop for j
      std::cout<<std::endl;
    } // end of loop for i
    return 0;
  } // end of function
int gift::readMatrix (const std::string inputFile, numericMatrix & getMat, std::string delims)
Referenced by gift::parameters::InitDrugSub2ProteinSub().
                                  {
    std::ifstream input (inputFile, std::ios::in);
    std::string line;
    std::vector<std::string> array;
    std::vector<double> tempRec;
    while(std::getline(input,line)){
      boost::algorithm::split(array,line,boost::is_any_of(delims));
      int arraylen = array.size();
      for(int i=0;i<arraylen;++i){
        std::string::size_type* idx = 0;
        tempRec.push_back(std::stod(array[i], idx));
      } // end of for
      getMat.push_back(tempRec);
      tempRec.clear();
    } // end of while
    // input.exceptions(std::ifstream::failbit | std::ifstream::badbit);
    // try {
    // input.open(inputFile, std::ifstream::in);
    // if (input.peek() == std::ifstream::traits_type::eof()){
    // std::cerr <<inputFile <<" is empty. " <<std::endl;
    // } // end of if
    // while(std::getline(input,line)){
    // boost::algorithm::split(array,line,boost::is_any_of(delims));
    // int arraylen = array.size();
    // for(int i=0;i<arraylen;++i){
    // std::string::size_type* idx = 0;
    // tempRec.push_back(std::stod(array[i], idx));
    // } // end of for
    // getMat.push_back(tempRec);
    // tempRec.clear();
    // } // end of while
    // } catch (std::ifstream::failure e) {
    // std::cerr <<"Exceptions open/read file "<<inputFile<<std::endl;
    // return 1;
    // } // end of catch
    return 0;
  }// end of function.
int gift::readName2IndexHash (const nameList fromNameList, name2IndexHash & name2Index)
Referenced by gift::parameters::InitDrugName2Index(), and gift::parameters::InitProteinName2Index().
                                                    {
    // fromNameList should be in order.
    if (fromNameList.empty()){
      std::cerr<<"The fromNameList is empty. "<<std::endl;
      return 1;
    } // end of if
    int recordIndex = 0;
    for(const auto fromName : fromNameList){
      name2Index.insert(std::pair<std::string,int>(fromName,recordIndex));
      ++recordIndex;
    } // end of loop fromNameList
    return 0;
  } // end of function
int gift::readNameListFromFile (const std::string inputFile, nameList & tonameList)
Referenced by gift::parameters::InitDrugName2Index(), gift::parameters::InitDrugSubNameList(), gift::parameters::InitPredictParameters(), gift::parameters::InitProteinName2Index(), and gift::parameters::InitProteinSubNameList().
                                                                           {
    // each line in the file represents one name.
    // line should end with "\n", not "[\r\t]\n"
    std::ifstream input (inputFile, std::ios::in);
    std::string line;
    while (std::getline(input,line)) {
      tonameList.push_back(line);
    } // end of while
    input.close();
    // input.exceptions(std::ifstream::failbit | std::ifstream::badbit);
    // try {
    // input.open(inputFile,std::ifstream::in);
    // if (input.peek() == std::ifstream::traits_type::eof()){
    // std::cerr << inputFile <<" is empty. "<<std::endl;
    // return 1;
    // } // end of if
    // while (std::getline(input,line)) {
    // tonameList.push_back(line);
    // } // end of while
    // input.close();
    // } catch (std::ifstream::failure e) {
    // std::cerr<<"Exceptions open/read file " << inputFile<<std::endl;
    // } // end of try catch
    return 0;
  } // end of function
int gift::readNameMatrixFromFile (const std::string inputFile, nameList & tonameList, IntArrayList & getFP, std::string delims)
Referenced by gift::parameters::InitPredictParameters().
                                                                   {
    std::ifstream input (inputFile, std::ios::in);
    std::string line;
    std::vector<std::string> array;
    std::vector<int> tempRec;
    while(std::getline(input,line)) {
      boost::algorithm::split(array,line,boost::is_any_of(delims));
      tonameList.push_back(array[0]); // first column is name.
      int arraylen = array.size();
      for(int i=1;i<arraylen;++i){
        if(array[i].compare("1") == 0) {
          tempRec.push_back(i-1); // Use i-1, since first column is name.
        } // end of if
      } // end of loop for i.
      getFP.push_back(tempRec);
      tempRec.clear();
    } // end of while
    // input.exceptions(std::ifstream::failbit | std::ifstream::badbit);
    // try {
    // input.open(inputFile, std::ifstream::in);
    // if (input.peek() == std::ifstream::traits_type::eof()) {
    // std::cerr<<inputFile<<" is empty. "<<std::endl;
    // return 1;
    // } // end of if
    // while(std::getline(input,line)) {
    // boost::algorithm::split(array,line,boost::is_any_of(delims));
    // tonameList.push_back(array[0]); // first column is name.
    // int arraylen = array.size();
    // for(int i=1;i<arraylen;++i){
    // if(array[i].compare("1") == 0) {
    // tempRec.push_back(i-1); // Use i-1, since first column is name.
    // } // end of if
    // } // end of loop for i.
    // getFP.push_back(tempRec);
    // tempRec.clear();
    // } // end of while
    // } catch (std::ifstream::failure e) {
    // std::cerr<<"Exceptions open/read file "<<inputFile<<std::endl;
    // return 1;
    // } // end of catch
    return 0;
  } // end of function
int gift::rowColFile (const std::string inputFile, rowCol & matrixRec, std::string delims)
References gift::rowCol::colNum, and gift::rowCol::rowNum.
Referenced by gift::parameters::parameters().
                                  {
    std::ifstream input (inputFile, std::ios::in);
    std::string line;
    int count = 0;
    std::vector<std::string> array;
    std::getline(input,line);
    ++count;
    boost::algorithm::split(array, line, boost::is_any_of(delims));
    matrixRec.colNum = array.size();
    // string getline func over istream.
    while(std::getline(input,line)){
      // QUESTION: how about empty line?
      ++count;
    } // end of while
    input.close();
    matrixRec.rowNum = count;
    matrixRec.colNum = array.size();
    // input.exceptions(std::ifstream::failbit | std::ifstream::badbit);
    // try {
    // input.open(inputFile,std::ifstream::in);
    // if (input.peek() == std::ifstream::traits_type::eof()){
    // std::cerr <<inputFile<<" is empty."<<std::endl;
    // return 1;
    // }
    // std::getline(input,line);
    // ++count;
    // boost::algorithm::split(array, line, boost::is_any_of(delims));
    // matrixRec.colNum = array.size();
    // // string getline func over istream.
    // while(std::getline(input,line)){
    // // QUESTION: how about empty line?
    // ++count;
    // } // end of while
    // input.close();
    // matrixRec.rowNum = count;
    // matrixRec.colNum = array.size();
    // } catch (std::ifstream::failure e) {
    // std::cerr << "Exceptions open/read file "<<inputFile<<std::endl;
    // return 1;
    // } // end of catch
    return 0;
  } // end of function.
const std::string gift::updateTime (`2016-03-06`)
Referenced by helpGift(), main(), and outRecord().
const std::string gift::version (`gift-2.0`)
Referenced by helpGift(), main(), and outRecord().
int gift::writeMatrix (const std::string outFileName, numericMatrix & resultMat, std::string delims)
Referenced by gift::EM::outTrainResult(), and gift::EM::outTrainVariance().
                                   {
    std::ofstream output (outFileName,std::ios::out);
    if (output.is_open()) {
      using boost::algorithm::join;
      using boost::adaptors::transformed;
      for (numericMatrix::iterator it = resultMat.begin();
           it != resultMat.end(); ++it) {
        output << join(*it | transformed(static_cast<std::string(*)(double)>
                                         (std::to_string)), delims);
        output<<std::endl;
      }// end of for
      output.close();
    } else {
      std::cerr<< "Error opening file " <<outFileName<<std::endl;
      return 1;
    } // end of if else
    return 0;
  }// end of function
Variable Documentation
IntArrayList gift::domain2proteinList
IntArrayList gift::drug2proteinList
IntArrayList gift::drug2subList
name2IndexHash gift::drugName2Index
Referenced by gift::EM::predictDrugs(), gift::EM::predictDrugsProteins(), and gift::EM::predictDrugsProteinsWithSubs().
nameList gift::drugNameList
Referenced by gift::EM::predictProteins(), and gift::EM::predictProteinsWithSubs().
numericMatrix gift::drugSub2proteinSubMatrix
Referenced by gift::EM::MStep().
nameList gift::drugSubNameList
std::vector< double > gift::loglikelyArray
Referenced by outRecord().
numericMatrix gift::observedDrug2ProteinMatrix
Referenced by gift::EM::EStep().
IntArrayList gift::predictDrug2SubList
Referenced by gift::EM::predictDrugsWithSubs(), gift::EM::predictDrugsWithSubsProteins(), and gift::EM::predictDrugsWithSubsProteinsWithSubs().
nameList gift::predictDrugNameList
Referenced by gift::EM::predictDrugs(), gift::EM::predictDrugsProteins(), gift::EM::predictDrugsProteinsWithSubs(), and gift::EM::predictEM().
nameList gift::predictDrugNameList_WithSubs
Referenced by gift::EM::predictDrugsWithSubs(), gift::EM::predictDrugsWithSubsProteins(), gift::EM::predictDrugsWithSubsProteinsWithSubs(), and gift::EM::predictEM().
IntArrayList gift::predictProtein2SubList
Referenced by gift::EM::predictDrugsProteinsWithSubs(), gift::EM::predictDrugsWithSubsProteinsWithSubs(), and gift::EM::predictProteinsWithSubs().
nameList gift::predictProteinNameList
Referenced by gift::EM::predictDrugsProteins(), gift::EM::predictDrugsWithSubsProteins(), gift::EM::predictEM(), and gift::EM::predictProteins().
nameList gift::predictProteinNameList_WithSubs
Referenced by gift::EM::predictDrugsProteinsWithSubs(), gift::EM::predictDrugsWithSubsProteinsWithSubs(), gift::EM::predictEM(), and gift::EM::predictProteinsWithSubs().
IntArrayList gift::protein2domainList
name2IndexHash gift::proteinName2Index
Referenced by gift::EM::predictDrugsProteins(), gift::EM::predictDrugsWithSubsProteins(), and gift::EM::predictProteins().
nameList gift::proteinNameList
Referenced by gift::EM::predictDrugs(), and gift::EM::predictDrugsWithSubs().
nameList gift::proteinSubNameList
const int gift::recLogLeastNum = 5
Referenced by gift::EM::trainEM().
IntArrayList gift::sub2drugList
numericMatrix gift::vardrugSub2proteinSubMatrix